CREATE TABLE Clientes(
    id_cliente NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) UNIQUE NOT NULL,
    clave VARCHAR2(200) NOT NULL,
    is_admin NUMBER(1) DEFAULT 0
);

CREATE TABLE Destino(
    id_destino NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    descripcion VARCHAR2(200),
    actividades VARCHAR2(200),
    costo NUMBER(12) NOT NULL
);

CREATE TABLE Paquetes(
    id_paquete NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    destino_id NUMBER NOT NULL,
    fecha_inicio VARCHAR2(100),
    fecha_fin VARCHAR2(100),
    precio_paquete NUMBER(12) NOT NULL,
    CONSTRAINT fk_paquete_destino
        FOREIGN KEY (destino_id)
        REFERENCES Destino(id_destino)
        ON DELETE CASCADE
);

CREATE TABLE Reservas(
    id_reserva NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente NUMBER NOT NULL,
    id_paquete NUMBER NOT NULL,
    fecha_reserva VARCHAR2(100),
    CONSTRAINT fk_reserva_cliente
        FOREIGN KEY (id_cliente)
        REFERENCES Clientes(id_cliente)
        ON DELETE CASCADE,
    CONSTRAINT fk_reserva_paquete
        FOREIGN KEY (id_paquete)
        REFERENCES Paquetes(id_paquete)
        ON DELETE CASCADE
);

DROP TABLE Reservas;
DROP TABLE Clientes;
DROP TABLE Paquetes_destino;
DROP TABLE Destino;
DROP TABLE Paquetes;