Create table Clientes(
    id_cliente NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100),
    clave VARCHAR2(150),
    is_admin NUMBER(1) DEFAULT 0
);

Create table Admin(
    id_admin NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100),
    email VARCHAR2(100) UNIQUE NOT NULL,
    AdminPassword VARCHAR2(40)
);

Create table Destino(
    id_destino NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100),
    descripcion VARCHAR2 (50),
    actividades VARCHAR2 (50),
    costo NUMBER (12)
);

Create table Paquetes(
    id_paquete NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    destino VARCHAR2(100),
    Fecha_inicio VARCHAR2(100),
    Fecha_fin VARCHAR2(100),
    precio_paquete NUMBER(10, 2) NOT NULL
);

Create table Paquetes_destino(
    id_paquetes_destino NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Paquete_id NUMBER(12),
    destino_id NUMBER(12) UNIQUE NOT NULL
);

Create table Reservas(
    id_reservas NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente NUMBER REFERENCES Clientes(id_cliente),
    id_destino NUMBER REFERENCES Destino(id_destino),
    Fecha_reserva NUMBER(12)
);




--Drop the nuke
DROP TABLE Reservas;
DROP TABLE Clientes;
DROP TABLE Paquetes_destino;
DROP TABLE Destino;
DROP TABLE Paquetes;
DROP TABLE Admin;


